hepsi: derle calistir
derle:
	g++ -I ./include/ -o ./lib/BagliKuyruk.o -c ./src/BagliKuyruk.cpp
	g++ -I ./include/ -o ./lib/BagliAgac.o -c ./src/BagliAgac.cpp
	
	
	g++ -I ./include/ -o ./bin/Source ./lib/BagliKuyruk.o ./lib/BagliAgac.o ./src/Source.cpp
	
calistir:
	./bin/Source
